//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drachenkatze.PresetMagician.VendorPresetParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drachenkatze.PresetMagician.VendorPresetParser.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hybrid3EndChunk {
            get {
                object obj = ResourceManager.GetObject("Hybrid3EndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LoomClassicEndChunk {
            get {
                object obj = ResourceManager.GetObject("LoomClassicEndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SynthMaster  vers=&quot;2.5.0d&quot; &gt;
        ///&lt;ENTRYDESCR  name=&quot;{{PATCHNAME}}&quot;  library=&quot;{{LIBRARYNAME}}&quot;  ATTRIB_VALUE_DATA=&quot;Description=2.5 default multi;size=0;&quot; &gt;
        ///&lt;/ENTRYDESCR&gt;
        /// &lt;SynthMasterEngineParamBlock &gt;
        ///&lt;MasterEngineBaseParamBlock  scaleName=&quot;Settings Library/Presets/Tuning File/Western/Equal Temperament.tun&quot;  HWprofile=&quot;&quot;  version=&quot;1&quot;  gain=&quot;3f3f7188&quot;  autoLdPatch=&quot;0&quot;  panic=&quot;0&quot;  mpe=&quot;0&quot;  tunV=&quot;43dc0000&quot;  pPan0=&quot;3f000000&quot;  pPan1=&quot;3f000000&quot;  pPan2=&quot;3f000000&quot;  pPan3=&quot;3f000000&quot;  pPan4=&quot;3f000000&quot;  pPan5=&quot;3f0000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OmnispherePatchTemplate {
            get {
                return ResourceManager.GetString("OmnispherePatchTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VacuumProEndChunk {
            get {
                object obj = ResourceManager.GetObject("VacuumProEndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Xpand2EndChunk {
            get {
                object obj = ResourceManager.GetObject("Xpand2EndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
