//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresetMagician.VendorPresetParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VendorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VendorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresetMagician.VendorPresetParser.Properties.VendorResources", typeof(VendorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AirFxSuiteEndChunk {
            get {
                object obj = ResourceManager.GetObject("AirFxSuiteEndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local serpent = require(&quot;serpent&quot;)
        ///
        ///function loadLibrary (data, bankSource, bankName, bankPath)
        ///    ---@param presets table
        ///    local ok, presets = serpent.load(data)
        ///
        ///    local parsedPresets = {};
        ///
        ///    for key, value in pairs(arr) do
        ///        local parsedPreset = {};
        ///
        ///        parsedPreset.insert(&quot;bankSource&quot;, bankSource)
        ///        parsedPreset.insert(&quot;index&quot;, key)
        ///        parsedPreset.insert(&quot;bankName&quot;, bankName)
        ///        parsedPreset.insert(&quot;bankName&quot;, bankPath)
        ///        parsedPreset.insert(&quot;pro [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AppliedAcousticSystems_LibraryParser {
            get {
                return ResourceManager.GetString("AppliedAcousticSystems_LibraryParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BoomEndChunk {
            get {
                object obj = ResourceManager.GetObject("BoomEndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Db33DefaultMidi {
            get {
                object obj = ResourceManager.GetObject("Db33DefaultMidi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Db33EndChunk {
            get {
                object obj = ResourceManager.GetObject("Db33EndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Db33FxDefaultMidi {
            get {
                object obj = ResourceManager.GetObject("Db33FxDefaultMidi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Db33FxEndChunk {
            get {
                object obj = ResourceManager.GetObject("Db33FxEndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Hybrid3EndChunk {
            get {
                object obj = ResourceManager.GetObject("Hybrid3EndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LoomClassicEndChunk {
            get {
                object obj = ResourceManager.GetObject("LoomClassicEndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local n, v = &quot;serpent&quot;, &quot;0.302&quot; -- (C) 2012-18 Paul Kulchenko; MIT License
        ///local c, d = &quot;Paul Kulchenko&quot;, &quot;Lua serializer and pretty printer&quot;
        ///local snum = {[tostring(1/0)]=&apos;1/0 --[[math.huge]]&apos;,[tostring(-1/0)]=&apos;-1/0 --[[-math.huge]]&apos;,[tostring(0/0)]=&apos;0/0&apos;}
        ///local badtype = {thread = true, userdata = true, cdata = true}
        ///local getmetatable = debug and debug.getmetatable or getmetatable
        ///local pairs = function(t) return next, t end -- avoid using __pairs in Lua 5.2+
        ///local keyword, globals, G = {}, {}, (_G or _E [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Lua_Serpent {
            get {
                return ResourceManager.GetString("Lua_Serpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MiniGrandDefaultMidi {
            get {
                object obj = ResourceManager.GetObject("MiniGrandDefaultMidi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MiniGrandEndChunk {
            get {
                object obj = ResourceManager.GetObject("MiniGrandEndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SynthMaster  vers=&quot;2.5.0d&quot; &gt;
        ///&lt;ENTRYDESCR  name=&quot;{{PATCHNAME}}&quot;  library=&quot;{{LIBRARYNAME}}&quot;  ATTRIB_VALUE_DATA=&quot;Description=2.5 default multi;size=0;&quot; &gt;
        ///&lt;/ENTRYDESCR&gt;
        /// &lt;SynthMasterEngineParamBlock &gt;
        ///&lt;MasterEngineBaseParamBlock  scaleName=&quot;Settings Library/Presets/Tuning File/Western/Equal Temperament.tun&quot;  HWprofile=&quot;&quot;  version=&quot;1&quot;  gain=&quot;3f3f7188&quot;  autoLdPatch=&quot;0&quot;  panic=&quot;0&quot;  mpe=&quot;0&quot;  tunV=&quot;43dc0000&quot;  pPan0=&quot;3f000000&quot;  pPan1=&quot;3f000000&quot;  pPan2=&quot;3f000000&quot;  pPan3=&quot;3f000000&quot;  pPan4=&quot;3f000000&quot;  pPan5=&quot;3f0000 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OmnispherePatchTemplate {
            get {
                return ResourceManager.GetString("OmnispherePatchTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RevealSound_Spire_Blank {
            get {
                object obj = ResourceManager.GetObject("RevealSound_Spire_Blank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_D50_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_D50_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_D50_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_D50_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_D50_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_D50_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JUNO106_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_JUNO106_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JUNO106_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_JUNO106_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JUNO106_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_JUNO106_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JUPITER_8_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_JUPITER-8_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JUPITER_8_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_JUPITER-8_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JUPITER_8_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_JUPITER-8_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JV_1080_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_JV-1080_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JV_1080_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_JV-1080_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JV_1080_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_JV-1080_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JX_3P_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_JX-3P_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JX_3P_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_JX-3P_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_JX_3P_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_JX-3P_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_PROMARS_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_PROMARS_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_PROMARS_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_PROMARS_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_PROMARS_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_PROMARS_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SH_101_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_SH-101_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SH_101_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_SH-101_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SH_101_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_SH-101_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SH_2_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_SH-2_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SH_2_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_SH-2_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SH_2_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_SH-2_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_DANCE_TRAX_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX DANCE TRAX_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_DANCE_TRAX_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX DANCE TRAX_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_DANCE_TRAX_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX DANCE TRAX_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_KEYBOARDS_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX KEYBOARDS_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_KEYBOARDS_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX KEYBOARDS_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_KEYBOARDS_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX KEYBOARDS_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_ORCHESTRA_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX ORCHESTRA_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_ORCHESTRA_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX ORCHESTRA_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_ORCHESTRA_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX ORCHESTRA_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_WORLD_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX WORLD_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_WORLD_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX WORLD_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SRX_WORLD_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_SRX WORLD_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SYSTEM_1_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_SYSTEM-1_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SYSTEM_1_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_SYSTEM-1_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SYSTEM_1_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_SYSTEM-1_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SYSTEM_100_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_SYSTEM-100_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SYSTEM_100_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_SYSTEM-100_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SYSTEM_100_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_SYSTEM-100_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SYSTEM_8_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_SYSTEM-8_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SYSTEM_8_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_SYSTEM-8_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_SYSTEM_8_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_SYSTEM-8_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_TB_303_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_TB-303_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_TB_303_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_TB-303_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_TB_303_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_TB-303_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_TR_808_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_TR-808_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_TR_808_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_TR-808_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_TR_808_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_TR-808_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_TR_909_ExportConfig {
            get {
                object obj = ResourceManager.GetObject("Roland_TR-909_ExportConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_TR_909_Script {
            get {
                object obj = ResourceManager.GetObject("Roland_TR-909_Script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roland_TR_909_Suffix {
            get {
                object obj = ResourceManager.GetObject("Roland_TR-909_Suffix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TheRiserEndChunk {
            get {
                object obj = ResourceManager.GetObject("TheRiserEndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] VacuumDefaultMidi {
            get {
                object obj = ResourceManager.GetObject("VacuumDefaultMidi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] VacuumEndChunk {
            get {
                object obj = ResourceManager.GetObject("VacuumEndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] VacuumProEndChunk {
            get {
                object obj = ResourceManager.GetObject("VacuumProEndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] VelvetEndChunk {
            get {
                object obj = ResourceManager.GetObject("VelvetEndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Xpand2DefaultMidi {
            get {
                object obj = ResourceManager.GetObject("Xpand2DefaultMidi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Xpand2EndChunk {
            get {
                object obj = ResourceManager.GetObject("Xpand2EndChunk", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
